# Generated by Django 3.1.5 on 2021-01-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='insert_date',
            field=models.DateTimeField(null=True),
        ),
    ]
